micronaut:
  application:
    name: proxy-server
  server:
    port: 8081
    cors:
      enabled: true

---
endpoints:
  all:
    path: self
    enabled: true
    sensitive: false

access-setup:

  time-to-live-minutes: 60
  check-period-seconds: 30

  proxy-endpoint-list:
    - endpoint-id: leifhttp
      endpoint-type: HTTP
      endpoint-host-name: localhost
      endpoint-port: 3000
    - endpoint-id: leif2
      endpoint-type: HTTP
      endpoint-url: http://localhost:3000
    - endpoint-id: leifftp
      endpoint-type: FTP
      endpoint-url: ftp://localhost:3999

  user-access-list:
    - user-id: leifaccess
      endpoint-id: leifhttp
      ip-address: ""
      token-path: "test"
      token: ""
    - user-id: leifaccess
      endpoint-id: leifhttp
      token-path: "test2"
      token: ""


proxy-server:
  main-host: localhost
  server-instances:
    - server-id: "test1"
      server-type: HTTP
      boot-address:
      port: 4000
      inactive-time-seconds: 60
      core-poolsize: 5
      maximum-poolsize: 20
      keep-alivetime: 5
    - server-id: "test2"
      server-type: FTP
      port: 4001
    - server-id: "test3"
      server-type: SFTP
      port: 4003